export const productList = [
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
  {
    idProduto: 1,
    dsProduto: 'Teste',
    dsUrl: '/fanta.jpg',
    vlPreco: 2,
  },
];
