export const productList = [
  {
    idProduct: 1,
    dsProduct: 'Fanta Uva',
    dsUrl: '/fanta.jpg',
    vlPrice: 3.5,
    qtStock: 50,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 2,
    dsProduct: 'Fanta Morango',
    dsUrl: '/fanta.jpg',
    vlPrice: 4.2,
    qtStock: 65,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 3,
    dsProduct: 'Fanta Abacaxi',
    dsUrl: '/fanta.jpg',
    vlPrice: 3.8,
    qtStock: 40,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 4,
    dsProduct: 'Fanta Maracujá',
    dsUrl: '/fanta.jpg',
    vlPrice: 5.1,
    qtStock: 55,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 5,
    dsProduct: 'Fanta Limão',
    dsUrl: '/fanta.jpg',
    vlPrice: 3.3,
    qtStock: 60,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 6,
    dsProduct: 'Fanta Maçã Verde',
    dsUrl: '/fanta.jpg',
    vlPrice: 6.7,
    qtStock: 45,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 7,
    dsProduct: 'Fanta Kiwi',
    dsUrl: '/fanta.jpg',
    vlPrice: 4.5,
    qtStock: 30,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 8,
    dsProduct: 'Fanta Pêssego',
    dsUrl: '/fanta.jpg',
    vlPrice: 3.9,
    qtStock: 70,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 9,
    dsProduct: 'Fanta Cereja',
    dsUrl: '/fanta.jpg',
    vlPrice: 5.5,
    qtStock: 50,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 10,
    dsProduct: 'Fanta Melancia',
    dsUrl: '/fanta.jpg',
    vlPrice: 4.1,
    qtStock: 60,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 11,
    dsProduct: 'Fanta Guaraná',
    dsUrl: '/fanta.jpg',
    vlPrice: 6.0,
    qtStock: 35,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 12,
    dsProduct: 'Fanta Caju',
    dsUrl: '/fanta.jpg',
    vlPrice: 4.8,
    qtStock: 55,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 13,
    dsProduct: 'Fanta Framboesa',
    dsUrl: '/fanta.jpg',
    vlPrice: 3.7,
    qtStock: 40,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 14,
    dsProduct: 'Fanta Melão',
    dsUrl: '/fanta.jpg',
    vlPrice: 5.2,
    qtStock: 65,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 15,
    dsProduct: 'Fanta Açaí',
    dsUrl: '/fanta.jpg',
    vlPrice: 3.5,
    qtStock: 50,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 16,
    dsProduct: 'Fanta Mirtilo',
    dsUrl: '/fanta.jpg',
    vlPrice: 4.9,
    qtStock: 45,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 17,
    dsProduct: 'Fanta Laranja',
    dsUrl: '/fanta.jpg',
    vlPrice: 6.5,
    qtStock: 30,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 18,
    dsProduct: 'Fanta Acerola',
    dsUrl: '/fanta.jpg',
    vlPrice: 3.6,
    qtStock: 70,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 19,
    dsProduct: 'Fanta Banana',
    dsUrl: '/fanta.jpg',
    vlPrice: 5.0,
    qtStock: 55,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
  {
    idProduct: 20,
    dsProduct: 'Fanta Manga',
    dsUrl: '/fanta.jpg',
    vlPrice: 4.0,
    qtStock: 60,
    brand: {
      idBrand: 'coca-cola',
      dsBrand: 'Coca Cola',
    },
    country: {
      idCountry: 'brazil',
      dsCountry: 'Brasil',
    },
    category: 'drink',
  },
];
